[project]
name = "bindsnet_docs"
dynamic = ["version"]
dependencies = [
  "sphinx==7.2.6",
  "sphinx_rtd_theme==1.3.0",
  "readthedocs-sphinx-search==0.3.1",
  "imagecodecs == 2023.9.18",
  "Jinja2 == 3.1.2",
  "wheel == 0.41.3",
]
